Revert "net: sysctl_net_core: Fix warning: 'one' defined but not used"
This reverts LSK commit f0387a70c1323f223343d73856ef36414c86d670.

Fix following net/core/sysctl_net_core.c build error:

  CC      net/core/sysctl_net_core.o
net/core/sysctl_net_core.c:372:15: error: 'one' undeclared here (not in a function)
   .extra1  = &one,
               ^
scripts/Makefile.build:257: recipe for target 'net/core/sysctl_net_core.o' failed
make[2]: *** [net/core/sysctl_net_core.o] Error 1

Signed-off-by: Amit Pundir <amit.pundir@linaro.org>